chisinau:
  lang: "ro"
  tz: Europe/Chisinau
  city: Chisinau
  city_local: Moldova
  country: MD
  lat: 47.0105
  lon: 28.8638
  feeds:
    #not refreshing - https://trm.md/ro/rss
    - https://timpul.md/feed
    - https://unimedia.info/ro/rss/all/
    - https://api.agora.md/rss